<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-05-15 at 00:01:07.
 */
class XGraphTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var XGraph
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new XGraph;

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown(): void
	{
		
	}

	/**
	 * Generated from @assert ('2022-05-10', 0) == array(PDate::Get('2022-05-08'), PDate::Get('2022-05-14')).
	 *
	 * @covers XGraph::GetWeekStartEnd
	 */
	public function testGetWeekStartEnd()
	{
		$this->assertEquals(
						array( PDate::Get( '2022-05-08' ), PDate::Get( '2022-05-14' ) ),
						XGraph::GetWeekStartEnd( '2022-05-10', 0 )
		);

	}

	/**
	 * Generated from @assert ('2022-05-10', 1) == array(PDate::Get('2022-05-09'), PDate::Get('2022-05-15')).
	 *
	 * @covers XGraph::GetWeekStartEnd
	 */
	public function testGetWeekStartEnd2()
	{
		$this->assertEquals(
						array( PDate::Get( '2022-05-09' ), PDate::Get( '2022-05-15' ) ),
						XGraph::GetWeekStartEnd( '2022-05-10', 1 )
		);

	}

	/**
	 * Generated from @assert ('2022-05-10', 2) == array(PDate::Get('2022-05-10'), PDate::Get('2022-05-16')).
	 *
	 * @covers XGraph::GetWeekStartEnd
	 */
	public function testGetWeekStartEnd3()
	{
		$this->assertEquals(
						array( PDate::Get( '2022-05-10' ), PDate::Get( '2022-05-16' ) ),
						XGraph::GetWeekStartEnd( '2022-05-10', 2 )
		);

	}

	/**
	 * Generated from @assert ('2022-05-10', 3) == array(PDate::Get('2022-05-04'), PDate::Get('2022-05-10')).
	 *
	 * @covers XGraph::GetWeekStartEnd
	 */
	public function testGetWeekStartEnd4()
	{
		$this->assertEquals(
						array( PDate::Get( '2022-05-04' ), PDate::Get( '2022-05-10' ) ),
						XGraph::GetWeekStartEnd( '2022-05-10', 3 )
		);

	}

	/**
	 * Generated from @assert ('2022-05-10', 4) == array(PDate::Get('2022-05-05'), PDate::Get('2022-05-11')).
	 *
	 * @covers XGraph::GetWeekStartEnd
	 */
	public function testGetWeekStartEnd5()
	{
		$this->assertEquals(
						array( PDate::Get( '2022-05-05' ), PDate::Get( '2022-05-11' ) ),
						XGraph::GetWeekStartEnd( '2022-05-10', 4 )
		);

	}

	/**
	 * Generated from @assert ('2022-05-10', 5) == array(PDate::Get('2022-05-06'), PDate::Get('2022-05-12')).
	 *
	 * @covers XGraph::GetWeekStartEnd
	 */
	public function testGetWeekStartEnd6()
	{
		$this->assertEquals(
						array( PDate::Get( '2022-05-06' ), PDate::Get( '2022-05-12' ) ),
						XGraph::GetWeekStartEnd( '2022-05-10', 5 )
		);

	}

	/**
	 * Generated from @assert ('2022-05-10', 6) == array(PDate::Get('2022-05-07'), PDate::Get('2022-05-13')).
	 *
	 * @covers XGraph::GetWeekStartEnd
	 */
	public function testGetWeekStartEnd7()
	{
		$this->assertEquals(
						array( PDate::Get( '2022-05-07' ), PDate::Get( '2022-05-13' ) ),
						XGraph::GetWeekStartEnd( '2022-05-10', 6 )
		);

	}

	/**
	 * @covers XGraph::getWorkerGroups
	 * @todo   Implement testGetWorkerGroups().
	 */
	public function testGetWorkerGroups()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetMyOrgs
	 * @todo   Implement testGetMyOrgs().
	 */
	public function testGetMyOrgs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetMyOrgsIDx
	 * @todo   Implement testGetMyOrgsIDx().
	 */
	public function testGetMyOrgsIDx()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetWorkerORGByID
	 * @todo   Implement testGetWorkerORGByID().
	 */
	public function testGetWorkerORGByID()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::getWorkerIDx
	 * @todo   Implement testGetWorkerIDx().
	 */
	public function testGetWorkerIDx()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::getWorkerORGIDs
	 * @todo   Implement testGetWorkerORGIDs().
	 */
	public function testGetWorkerORGIDs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::getWorkerIDxByOrgs
	 * @todo   Implement testGetWorkerIDxByOrgs().
	 */
	public function testGetWorkerIDxByOrgs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::getWorkerIDsByOrg
	 * @todo   Implement testGetWorkerIDsByOrg().
	 */
	public function testGetWorkerIDsByOrg()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetOrgUser
	 * @todo   Implement testGetOrgUser().
	 */
	public function testGetOrgUser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetApprove
	 * @todo   Implement testGetApprove().
	 */
	public function testGetApprove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetAdminApprove
	 * @todo   Implement testGetAdminApprove().
	 */
	public function testGetAdminApprove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetOrgData
	 * @todo   Implement testGetOrgData().
	 */
	public function testGetOrgData()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetGraphDays
	 * @todo   Implement testGetGraphDays().
	 */
	public function testGetGraphDays()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetWorkerWeekHours
	 * @todo   Implement testGetWorkerWeekHours().
	 */
	public function testGetWorkerWeekHours()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::GetWorkerWeekRate
	 * @todo   Implement testGetWorkerWeekRate().
	 */
	public function testGetWorkerWeekRate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

	/**
	 * @covers XGraph::DayOfYear2Date
	 * @todo   Implement testDayOfYear2Date().
	 */
	public function testDayOfYear2Date()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);

	}

}
